"""add lesson content and question models

Revision ID: 6ee13e1a9595
Revises: 4046e4c8c3ef
Create Date: 2026-05-08 21:00:43.448398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee13e1a9595'
down_revision: Union[str, Sequence[str], None] = '4046e4c8c3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_question_position')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'position', name='uq_option_position')
    )
    op.create_index(op.f('ix_answer_options_id'), 'answer_options', ['id'], unique=False)
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.add_column('lessons', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_url')
    op.drop_column('lessons', 'body')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_index(op.f('ix_answer_options_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
